namespace CodexToolkit.Tests;

public class InstallationTests
{
    static string Toolkit => AgentTool.FindToolkit();
    [Fact] public void DryRunNeverCreatesHome() { var home = Path.Combine(Path.GetTempPath(), "toolkit-no-write-" + Guid.NewGuid().ToString("N")); Assert.Equal(0, Installer.Run(Toolkit, home, null, "install", true, false).ExitCode); Assert.False(Directory.Exists(home)); }
    [Fact] public void ConflictsMakeNoPartialInstallation() { using var repo = new TemporaryGitRepository(); var home = Path.Combine(repo.Root, "home"); Directory.CreateDirectory(Path.Combine(home, ".codex")); var file = Path.Combine(home, ".codex/AGENTS.md"); File.WriteAllText(file, "mine"); Assert.Equal(1, Installer.Run(Toolkit, home, null, "install", false, false).ExitCode); Assert.Equal("mine", File.ReadAllText(file)); Assert.False(Directory.Exists(Path.Combine(home, ".agents"))); }
    [Fact] public void InstallUpdateIdempotentAndUninstallPreservesReplacement() { using var repo = new TemporaryGitRepository(); var home = Path.Combine(repo.Root, "home"); Assert.Equal(0, Installer.Run(Toolkit, home, null, "install", false, true).ExitCode); Assert.Equal(0, Installer.Run(Toolkit, home, null, "update", false, true).ExitCode); var file = Path.Combine(home, ".codex/AGENTS.md"); File.Delete(file); File.WriteAllText(file, "my replacement"); Assert.Equal(0, Installer.Run(Toolkit, home, null, "uninstall", false, false).ExitCode); Assert.Equal("my replacement", File.ReadAllText(file)); Assert.False(File.Exists(Path.Combine(home, ".local/bin/codex-agent-tool"))); }
    [Fact] public void RefusesSymlinkedDestinationParent() { using var repo = new TemporaryGitRepository(); var home = Path.Combine(repo.Root, "home"); var elsewhere = Path.Combine(repo.Root, "elsewhere"); Directory.CreateDirectory(home); Directory.CreateDirectory(elsewhere); Directory.CreateSymbolicLink(Path.Combine(home, ".codex"), elsewhere); Assert.Throws<IOException>(() => Installer.Run(Toolkit, home, null, "install", false, false)); Assert.Empty(Directory.GetFiles(elsewhere)); }
    [Fact] public void TamperedOwnershipCannotDeleteArbitraryFile() { using var repo = new TemporaryGitRepository(); var home = Path.Combine(repo.Root, "home"); Installer.Run(Toolkit, home, null, "install", false, false); var path = Path.Combine(home, ".codex/codex-toolkit-install.json"); var manifest = System.Text.Json.JsonSerializer.Deserialize<InstallManifest>(File.ReadAllText(path), AgentTool.Json)!; var victim = Path.Combine(repo.Root, "victim"); File.WriteAllText(victim, "mine"); manifest.Entries.Add(new(victim, Path.Combine(Toolkit, "global/AGENTS.md"), false)); File.WriteAllText(path, System.Text.Json.JsonSerializer.Serialize(manifest, AgentTool.Json)); Assert.Throws<IOException>(() => Installer.Run(Toolkit, home, null, "uninstall", false, false)); Assert.Equal("mine", File.ReadAllText(victim)); }
    [Fact] public void UninstallRemovesStaleOwnedLink() { using var repo = new TemporaryGitRepository(); var home = Path.Combine(repo.Root, "home"); Installer.Run(Toolkit, home, null, "install", false, false); var path = Path.Combine(home, ".codex/codex-toolkit-install.json"); var manifest = System.Text.Json.JsonSerializer.Deserialize<InstallManifest>(File.ReadAllText(path), AgentTool.Json)!; var source = Path.Combine(Toolkit, "agents", "obsolete.toml"); var destination = Path.Combine(home, ".codex", "agents", "obsolete.toml"); File.CreateSymbolicLink(destination, source); manifest.Entries.Add(new(destination, source, false)); File.WriteAllText(path, System.Text.Json.JsonSerializer.Serialize(manifest, AgentTool.Json)); Assert.Equal(0, Installer.Run(Toolkit, home, null, "uninstall", false, false).ExitCode); Assert.False(File.Exists(destination)); }
}
